[package]
name = "tv-menu"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tvmenu"
path = "src/main.rs"

[dependencies]
entries = { path = "../lib/entries" }
config = { path = "../lib/config" }
widgets = { path = "../lib/widgets" }
eframe = { version="0.32", features=["default"] }
