[package]
name = "tv-menu"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "tvmenu"
path = "src/main.rs"

[dependencies]
iced= { version="0.13", features = [ "image","advanced" ] }
entries = { path = "../lib/entries" }
config = { path = "../lib/config" }
